---
- name: Install common shell packages
  become: true
  apt:
    pkg:
      - git
      - tree
      - make
      - wget
      - curl
      - zip
      - unzip
      - seahorse-nautilus
      - fzf
      - ripgrep
      - silversearcher-ag
      - jq
      - fonts-powerline
      - dconf-cli  # for gogh colors
      - uuid-runtime  # for gogh colors
      - tmux
      - hunspell

- name: Create default gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: '~/.gitconfig'
    mode: '0644'
    backup: true